spring:
    application:
        name: cleanArchitecture-demo

    datasource:
        url: jdbc:postgresql://localhost:5432/clinic
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
